baseURL = 'https://solinnen.github.io'
languageCode = 'en-US'
title = 'Beronika Solinnen'
summaryLength = 20

[markup.highlight]
  style = 'autumn'

[params]
  telegramURL = 'https://t.me/Solinnen'
  description = 'I am a full-stack software engineer specializing in backend development.'

disableHugoGeneratorInject = true
