baseURL = 'https://solinnen.github.io'
languageCode = 'en-US'
title = 'Beronika Solinnen'

[markup]
  [markup.highlight]
    style = 'native'
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [['$', '$']]
          block = [['$$', '$$']]

[params]
  staticURL = 'https://solinnen.github.io'
  telegramURL = 'https://t.me/Solinnen'
  description = 'Full-stack software engineer specializing in backend development.'

disableHugoGeneratorInject = true

[taxonomies]
  tag = ""
  category = ""

[sitemap]
  changeFreq = 'daily'
  filename = 'sitemap.xml'
  priority = -1


