baseURL = 'https://solinnen.github.io'
languageCode = 'en-US'
title = 'Beronika Solinnen'
summaryLength = 20

[markup.highlight]
  style = 'native'

[params]
  staticURL = 'https://solinnen.github.io'
  telegramURL = 'https://t.me/Solinnen'
  description = 'Full-stack software engineer specializing in backend development.'

disableHugoGeneratorInject = true
